/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./popup.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Material 3 Expressive - Dark Theme
        'md-dark': {
          primary: '#A8C7FA',
          'on-primary': '#003258',
          'primary-container': '#004A77',
          'on-primary-container': '#D3E4FF',
          secondary: '#B8C8DA',
          'on-secondary': '#23323F',
          'secondary-container': '#394857',
          'on-secondary-container': '#D4E3F7',
          tertiary: '#D1BFE7',
          'on-tertiary': '#36294C',
          'tertiary-container': '#4D3F64',
          'on-tertiary-container': '#EDE0FF',
          error: '#FFB4AB',
          'on-error': '#690005',
          'error-container': '#93000A',
          'on-error-container': '#FFDAD6',
          background: '#1A1C1E',
          'on-background': '#E2E2E6',
          surface: '#1A1C1E',
          'on-surface': '#E2E2E6',
          'surface-variant': '#41484D',
          'on-surface-variant': '#C1C7CE',
          outline: '#8B9297',
          'outline-variant': '#41484D',
          'surface-container-lowest': '#0F1113',
          'surface-container-low': '#1A1C1E',
          'surface-container': '#1E2022',
          'surface-container-high': '#282A2C',
          'surface-container-highest': '#323437',
        },
        // Material 3 Expressive - Light Theme
        'md-light': {
          primary: '#005FAE',
          'on-primary': '#FFFFFF',
          'primary-container': '#D3E4FF',
          'on-primary-container': '#001C3A',
          secondary: '#51606F',
          'on-secondary': '#FFFFFF',
          'secondary-container': '#D4E3F7',
          'on-secondary-container': '#0D1D2A',
          tertiary: '#68548E',
          'on-tertiary': '#FFFFFF',
          'tertiary-container': '#EDE0FF',
          'on-tertiary-container': '#221634',
          error: '#BA1A1A',
          'on-error': '#FFFFFF',
          'error-container': '#FFDAD6',
          'on-error-container': '#410002',
          background: '#F8F9FD',
          'on-background': '#1A1C1E',
          surface: '#F8F9FD',
          'on-surface': '#1A1C1E',
          'surface-variant': '#DFE2EB',
          'on-surface-variant': '#43474E',
          outline: '#73777F',
          'outline-variant': '#C3C7CF',
          'surface-container-lowest': '#FFFFFF',
          'surface-container-low': '#F2F3F7',
          'surface-container': '#ECEEF2',
          'surface-container-high': '#E6E8EC',
          'surface-container-highest': '#E1E2E6',
        },
      },
      fontFamily: {
        sans: ['Roboto', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['Roboto Mono', 'monospace'],
      },
      fontSize: {
        'display-large': ['57px', { lineHeight: '64px', fontWeight: '400' }],
        'display-medium': ['45px', { lineHeight: '52px', fontWeight: '400' }],
        'display-small': ['36px', { lineHeight: '44px', fontWeight: '400' }],
        'headline-large': ['32px', { lineHeight: '40px', fontWeight: '400' }],
        'headline-medium': ['28px', { lineHeight: '36px', fontWeight: '400' }],
        'headline-small': ['24px', { lineHeight: '32px', fontWeight: '400' }],
        'title-large': ['22px', { lineHeight: '28px', fontWeight: '500' }],
        'title-medium': ['16px', { lineHeight: '24px', fontWeight: '500' }],
        'title-small': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-large': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-medium': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-small': ['11px', { lineHeight: '16px', fontWeight: '500' }],
        'body-large': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-medium': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-small': ['12px', { lineHeight: '16px', fontWeight: '400' }],
      },
      borderRadius: {
        'md-none': '0px',
        'md-xs': '4px',
        'md-sm': '8px',
        'md-md': '12px',
        'md-lg': '16px',
        'md-xl': '28px',
        'md-full': '9999px',
      },
      boxShadow: {
        'md-1': '0px 1px 2px 0px rgba(0, 0, 0, 0.3), 0px 1px 3px 1px rgba(0, 0, 0, 0.15)',
        'md-2': '0px 1px 2px 0px rgba(0, 0, 0, 0.3), 0px 2px 6px 2px rgba(0, 0, 0, 0.15)',
        'md-3': '0px 4px 8px 3px rgba(0, 0, 0, 0.15), 0px 1px 3px 0px rgba(0, 0, 0, 0.3)',
        'md-4': '0px 6px 10px 4px rgba(0, 0, 0, 0.15), 0px 2px 3px 0px rgba(0, 0, 0, 0.3)',
        'md-5': '0px 8px 12px 6px rgba(0, 0, 0, 0.15), 0px 4px 4px 0px rgba(0, 0, 0, 0.3)',
      },
      animation: {
        'ripple': 'ripple 600ms cubic-bezier(0.4, 0, 0.2, 1)',
        'fade-in': 'fadeIn 300ms cubic-bezier(0.4, 0, 0.2, 1)',
        'slide-up': 'slideUp 400ms cubic-bezier(0.05, 0.7, 0.1, 1)',
        'scale-in': 'scaleIn 300ms cubic-bezier(0.05, 0.7, 0.1, 1)',
        'bounce-in': 'bounceIn 500ms cubic-bezier(0.68, -0.55, 0.265, 1.55)',
      },
      keyframes: {
        ripple: {
          '0%': { transform: 'scale(0)', opacity: '0.5' },
          '100%': { transform: 'scale(4)', opacity: '0' },
        },
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          '0%': { transform: 'translateY(16px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        bounceIn: {
          '0%': { transform: 'scale(0.3)', opacity: '0' },
          '50%': { transform: 'scale(1.05)' },
          '70%': { transform: 'scale(0.9)' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
